# Source from any directory. Credentials are generated by the local operator,
# stored outside this checkout and never inherited from an ambient database URL.
export PATH=/workspace/.onboarding-tools/node_modules/.bin:$PATH
export npm_config_cache=/workspace/.npm-cache
export XDG_CACHE_HOME=/workspace/.cache
export XDG_DATA_HOME=/workspace/.local/share
export npm_config_devdir=/workspace/.cache/node-gyp
if [ ! -r /workspace/iam-local/services.env ]; then
  echo "Missing /workspace/iam-local/services.env; restore existing local credentials before starting persistent services." >&2
  return 1
fi
set -a
. /workspace/iam-local/services.env
set +a
if [ -z "${IAM_POSTGRES_PASSWORD:-}" ] || [ -z "${IAM_REDIS_PASSWORD:-}" ]; then
  echo "Local PostgreSQL and Redis credentials must both be configured." >&2
  return 1
fi
export DATABASE_URL="postgresql://iam_local:${IAM_POSTGRES_PASSWORD}@127.0.0.1:55432/iam_local?schema=public"
export IAM_TEST_DATABASE_URL="postgresql://iam_local:${IAM_POSTGRES_PASSWORD}@127.0.0.1:55432/iam_test?schema=public"
export REDIS_URL="redis://:${IAM_REDIS_PASSWORD}@127.0.0.1:56379"
